# PowerShell script to check server status
Write-Host "=== CHECKING SERVER STATUS ==="
Write-Host ""
Write-Host "Please run these commands on your server to check if migration completed:"
Write-Host ""
Write-Host "ssh root@23.88.113.154"
Write-Host ""
Write-Host "Then run:"
Write-Host "cd /opt/victoriaocara"
Write-Host "ls -la migrate-all-translations-to-admin.sh"
Write-Host "tail -10 /var/log/auto-pull.log"
Write-Host "git log --oneline -3"
Write-Host ""
Write-Host "If the script exists, run it manually:"
Write-Host "chmod +x migrate-all-translations-to-admin.sh"
Write-Host "./migrate-all-translations-to-admin.sh"